name: Build project and docs

on:
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci        
      - name: Build Vue.js app
        run: npm run build
      - name: Build VitePress docs
        run: |
          npm run docs:build
          mv ./docs/.vitepress/dist ./dist/docs